import "./globals.css";
import  Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="  min-h-screen flex flex-col">
        <Header />
        <main className="grow p-4 flex flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
